#CFLAGS=-Wall -g `pkg-config --cflags gtk+-2.0 glib-2.0`
#LIBS=`pkg-config --libs gtk+-2.0 glib-2.0`

all:
	gcc -Wall -g  main.c config.c lock.c notification.c notification_sound.c ping.c path.c -o comrade  ../lib/linux/x86_64/libjsmn.a ../lib/linux/x86_64/libgorilla.a -lm -lpthread -lnotify `pkg-config --libs --cflags glib-2.0 gtk+-2.0` ../lib/linux/x86_64/libopenal.so 

clean:
	rm -i -f comrade 

